function configurar_funciones_matlab(modelo)
% Configura el código de las funciones MATLAB en los bloques

fprintf('Configurando funciones MATLAB en los bloques...\n');

%% ========================================
%% FUNCIONES PARA SUBSISTEMA AM
%% ========================================

sys_am = [modelo '/AM_Sistema'];

%% FUNCIÓN 1: Generador de Llegadas
fprintf('  - Configurando Generador de Llegadas...\n');

codigo_generador = [...
'function [nueva_llegada, tiempo_siguiente] = Generador_Llegadas(t, u, lambda)' newline...
'% Genera llegadas según proceso de Poisson' newline...
'' newline...
'persistent tiempo_proxima_llegada;' newline...
'persistent contador;' newline...
'' newline...
'if isempty(tiempo_proxima_llegada)' newline...
'    tiempo_proxima_llegada = 0;' newline...
'    contador = 0;' newline...
'end' newline...
'' newline...
'nueva_llegada = 0;' newline...
'' newline...
'% Verificar si es momento de generar llegada' newline...
'if t >= tiempo_proxima_llegada' newline...
'    nueva_llegada = 1;' newline...
'    contador = contador + 1;' newline...
'    ' newline...
'    % Calcular próxima llegada (distribución exponencial)' newline...
'    tiempo_entre_llegadas = -log(u) / lambda;' newline...
'    tiempo_proxima_llegada = t + tiempo_entre_llegadas;' newline...
'end' newline...
'' newline...
'tiempo_siguiente = tiempo_proxima_llegada;' newline...
];

% No podemos escribir directamente, hay que hacerlo manual
fprintf('    CÓDIGO PARA: %s/Generador_Llegadas\n', sys_am);
fprintf('    Copia este código en el bloque MATLAB Function:\n\n');
fprintf('%s\n', codigo_generador);
fprintf('    ---\n\n');

%% FUNCIÓN 2: Asignar Cliente
fprintf('  - Configurando Asignar Cliente...\n');

codigo_asignar = [...
'function [BW_disponible, es_movil] = Asignar_Cliente(u_tipo, u_bw, prob_movil)' newline...
'% Asigna ancho de banda y tipo de cliente' newline...
'' newline...
'% Parámetros' newline...
'media_BW_desktop = 150;' newline...
'std_BW_desktop = 30;' newline...
'media_BW_movil = 80;' newline...
'std_BW_movil = 25;' newline...
'' newline...
'% Determinar tipo de cliente' newline...
'if u_tipo < prob_movil' newline...
'    es_movil = 1;' newline...
'    media = media_BW_movil;' newline...
'    std_dev = std_BW_movil;' newline...
'else' newline...
'    es_movil = 0;' newline...
'    media = media_BW_desktop;' newline...
'    std_dev = std_BW_desktop;' newline...
'end' newline...
'' newline...
'% Generar BW usando Box-Muller' newline...
'z = sqrt(-2*log(u_bw)) * cos(2*pi*u_bw);' newline...
'BW_disponible = media + std_dev * z;' newline...
'' newline...
'% BW mínimo 32 kbps' newline...
'BW_disponible = max(BW_disponible, 32);' newline...
];

fprintf('    CÓDIGO PARA: %s/Asignar_Cliente\n', sys_am);
fprintf('    Copia este código en el bloque MATLAB Function:\n\n');
fprintf('%s\n', codigo_asignar);
fprintf('    ---\n\n');

%% FUNCIÓN 3: Selector de Velocidad
fprintf('  - Configurando Selector de Velocidad...\n');

codigo_selector = [...
'function velocidad_asignada = Selector_Velocidad(BW_disponible)' newline...
'% Selecciona la velocidad óptima según BW del cliente' newline...
'' newline...
'velocidades = [128, 96, 64];' newline...
'margen_seguridad = 1.1; % 10% margen' newline...
'' newline...
'velocidad_asignada = 64; % Default: la más baja' newline...
'' newline...
'% Buscar la velocidad más alta que el cliente puede soportar' newline...
'for i = 1:length(velocidades)' newline...
'    if BW_disponible >= velocidades(i) * margen_seguridad' newline...
'        velocidad_asignada = velocidades(i);' newline...
'        break;' newline...
'    end' newline...
'end' newline...
];

fprintf('    CÓDIGO PARA: %s/Selector_Velocidad\n', sys_am);
fprintf('    Copia este código en el bloque MATLAB Function:\n\n');
fprintf('%s\n', codigo_selector);
fprintf('    ---\n\n');

%% FUNCIÓN 4-6: Colas M/M/c (una por cada velocidad)
fprintf('  - Configurando Colas M/M/c...\n');

velocidades = [128, 96, 64];

for v = 1:length(velocidades)
    vel = velocidades(v);
    
    codigo_cola = [...
    'function [aceptado, rechazado, en_cola, serv_ocupados, slow_listener] = Cola_MMc_' num2str(vel) 'kbps(llegada, BW_cliente, velocidad_stream, t)' newline...
    '% Sistema M/M/c con 3 servidores para ' num2str(vel) ' kbps' newline...
    '' newline...
    'persistent cola;' newline...
    'persistent servidores_libres;' newline...
    'persistent clientes_en_servicio;' newline...
    'persistent cola_fifo;' newline...
    'persistent contadores;' newline...
    '' newline...
    '% Inicialización' newline...
    'if isempty(cola)' newline...
    '    cola = 0;' newline...
    '    servidores_libres = 3;' newline...
    '    clientes_en_servicio = zeros(3, 2); % [tiempo_fin, BW_cliente]' newline...
    '    cola_fifo = [];' newline...
    '    contadores = struct();' newline...
    '    contadores.llegadas = 0;' newline...
    '    contadores.atendidos = 0;' newline...
    '    contadores.rechazados_BW = 0;' newline...
    '    contadores.rechazados_cola = 0;' newline...
    'end' newline...
    '' newline...
    'aceptado = 0;' newline...
    'rechazado = 0;' newline...
    'slow_listener = 0;' newline...
    '' newline...
    '% Procesar finalizaciones de servicio' newline...
    'for i = 1:3' newline...
    '    if clientes_en_servicio(i,1) > 0 && t >= clientes_en_servicio(i,1)' newline...
    '        % Liberar servidor' newline...
    '        clientes_en_servicio(i,:) = [0, 0];' newline...
    '        servidores_libres = servidores_libres + 1;' newline...
    '        ' newline...
    '        % Atender de la cola si hay clientes' newline...
    '        if cola > 0 && ~isempty(cola_fifo)' newline...
    '            cola = cola - 1;' newline...
    '            cliente = cola_fifo(1,:);' newline...
    '            cola_fifo(1,:) = [];' newline...
    '            ' newline...
    '            servidores_libres = servidores_libres - 1;' newline...
    '            mu = 1/300;' newline...
    '            tiempo_servicio = -log(rand()) / mu;' newline...
    '            clientes_en_servicio(i,:) = [t + tiempo_servicio, cliente(2)];' newline...
    '            contadores.atendidos = contadores.atendidos + 1;' newline...
    '        end' newline...
    '    end' newline...
    'end' newline...
    '' newline...
    '% Procesar nueva llegada' newline...
    'if llegada == 1' newline...
    '    contadores.llegadas = contadores.llegadas + 1;' newline...
    '    ' newline...
    '    % Verificar Slow-Listener' newline...
    '    if BW_cliente < velocidad_stream * 1.1' newline...
    '        rechazado = 1;' newline...
    '        slow_listener = 1;' newline...
    '        contadores.rechazados_BW = contadores.rechazados_BW + 1;' newline...
    '    else' newline...
    '        % Verificar disponibilidad de servidor' newline...
    '        if servidores_libres > 0' newline...
    '            aceptado = 1;' newline...
    '            servidores_libres = servidores_libres - 1;' newline...
    '            ' newline...
    '            % Generar tiempo de servicio' newline...
    '            mu = 1/300;' newline...
    '            tiempo_servicio = -log(rand()) / mu;' newline...
    '            ' newline...
    '            % Asignar a servidor libre' newline...
    '            for i = 1:3' newline...
    '                if clientes_en_servicio(i,1) == 0' newline...
    '                    clientes_en_servicio(i,:) = [t + tiempo_servicio, BW_cliente];' newline...
    '                    break;' newline...
    '                end' newline...
    '            end' newline...
    '            ' newline...
    '            contadores.atendidos = contadores.atendidos + 1;' newline...
    '        else' newline...
    '            % Agregar a cola si hay espacio' newline...
    '            if cola < 50' newline...
    '                cola = cola + 1;' newline...
    '                cola_fifo = [cola_fifo; t, BW_cliente];' newline...
    '            else' newline...
    '                rechazado = 1;' newline...
    '                contadores.rechazados_cola = contadores.rechazados_cola + 1;' newline...
    '            end' newline...
    '        end' newline...
    '    end' newline...
    'end' newline...
    '' newline...
    'en_cola = cola;' newline...
    'serv_ocupados = 3 - servidores_libres;' newline...
    ];
    
    fprintf('    CÓDIGO PARA: %s/Cola_MMc_%dkbps\n', sys_am, vel);
    fprintf('    Copia este código en el bloque MATLAB Function:\n\n');
    fprintf('%s\n', codigo_cola);
    fprintf('    ---\n\n');
end

%% FUNCIÓN 7: Recolector de Estadísticas
fprintf('  - Configurando Recolector de Estadísticas...\n');

codigo_stats = [...
'function [stats_salida] = Recolector_Stats(aceptado_128, rechazado_128, slow_128, aceptado_96, rechazado_96, slow_96, aceptado_64, rechazado_64, slow_64)' newline...
'% Recolecta y consolida estadísticas de las 3 velocidades' newline...
'' newline...
'persistent stats;' newline...
'' newline...
'if isempty(stats)' newline...
'    stats = zeros(9,1);' newline...
'    % [total_aceptados, total_rechazados, total_slow_listeners,' newline...
'    %  accept_128, reject_128, slow_128,' newline...
'    %  accept_96, reject_96, slow_96,' newline...
'    %  accept_64, reject_64, slow_64]' newline...
'end' newline...
'' newline...
'% Actualizar contadores' newline...
'stats(1) = stats(1) + aceptado_128 + aceptado_96 + aceptado_64;' newline...
'stats(2) = stats(2) + rechazado_128 + rechazado_96 + rechazado_64;' newline...
'stats(3) = stats(3) + slow_128 + slow_96 + slow_64;' newline...
'' newline...
'stats(4) = stats(4) + aceptado_128;' newline...
'stats(5) = stats(5) + rechazado_128;' newline...
'stats(6) = stats(6) + slow_128;' newline...
'' newline...
'stats(7) = stats(7) + aceptado_96;' newline...
'stats(8) = stats(8) + rechazado_96;' newline...
'stats(9) = stats(9) + slow_96;' newline...
'' newline...
'stats(10) = stats(10) + aceptado_64;' newline...
'stats(11) = stats(11) + rechazado_64;' newline...
'stats(12) = stats(12) + slow_64;' newline...
'' newline...
'% Calcular tasa de éxito' newline...
'total_llegadas = stats(1) + stats(2);' newline...
'if total_llegadas > 0' newline...
'    tasa_exito = stats(1) / total_llegadas;' newline...
'    tasa_slow = stats(3) / total_llegadas;' newline...
'else' newline...
'    tasa_exito = 0;' newline...
'    tasa_slow = 0;' newline...
'end' newline...
'' newline...
'% Salida compacta: [tasa_exito, tasa_slow_listeners, total_atendidos]' newline...
'stats_salida = [tasa_exito; tasa_slow; stats(1)];' newline...
];

fprintf('    CÓDIGO PARA: %s/Recolector_Stats\n', sys_am);
fprintf('    Copia este código en el bloque MATLAB Function:\n\n');
fprintf('%s\n', codigo_stats);
fprintf('    ---\n\n');

fprintf('\n========================================\n');
fprintf('IMPORTANTE: Repite las mismas funciones para el subsistema FM\n');
fprintf('Solo cambia "AM" por "FM" en los nombres\n');
fprintf('========================================\n\n');

fprintf('Configuración completada.\n');
fprintf('Ahora debes:\n');
fprintf('1. Abrir el modelo: open_system(''%s'')\n', modelo);
fprintf('2. Hacer doble clic en cada bloque MATLAB Function\n');
fprintf('3. Copiar y pegar el código correspondiente\n');
fprintf('4. Conectar las líneas de señal entre bloques\n');

end