function generar_codigo_funciones(parametros)
% Genera código listo para copiar-pegar en los bloques MATLAB Function

% Código para InterArrival_General
codigo_interarrival = sprintf(...
    'function t = InterArrival_General(~)\n' ...
    '%% Generado automáticamente por bootstrap_inicial.m\n' ...
    '%% Fecha: %s\n' ...
    'persistent init mu_log sigma_log;\n' ...
    'if isempty(init)\n' ...
    '    mu_log = %.6f;\n' ...
    '    sigma_log = %.6f;\n' ...
    '    init = 1;\n' ...
    'end\n' ...
    't = lognrnd(mu_log, sigma_log);\n' ...
    'if t <= 0 || t > 3600\n' ...
    '    t = 10;\n' ...
    'end\n' ...
    'end', datestr(now), parametros.mu_log, parametros.sigma_log);

% Código para Assign_Cliente  
codigo_assign = sprintf(...
    'function [emisora, bitrate, isSlow] = Assign_Cliente(trigger)\n' ...
    '%% Generado automáticamente por iniciar_presimulacion.m\n' ...
    '%% Fecha: %s\n' ...
    'persistent init prob_AM prob_slow_AM prob_slow_FM;\n' ...
    'if isempty(init)\n' ...
    '    prob_AM = %.6f;\n' ...
    '    prob_slow_AM = %.6f;\n' ...
    '    prob_slow_FM = %.6f;\n' ...
    '    init = 1;\n' ...
    'end\n' ...
    '\n' ...
    'r = rand();\n' ...
    'if r < prob_AM\n' ...
    '    emisora = 0; %% AM\n' ...
    'else\n' ...
    '    emisora = 1; %% FM\n' ...
    'end\n' ...
    '\n' ...
    'if emisora == 0\n' ...
    '    prob_slow = prob_slow_AM;\n' ...
    'else\n' ...
    '    prob_slow = prob_slow_FM;\n' ...
    'end\n' ...
    '\n' ...
    '%% Distribución de bitrates (ajusta según necesidad)\n' ...
    'r_bit = rand();\n' ...
    'if r_bit < 0.6\n' ...
    '    bitrate = 128;\n' ...
    'elseif r_bit < 0.9\n' ...
    '    bitrate = 96;\n' ...
    'else\n' ...
    '    bitrate = 64;\n' ...
    'end\n' ...
    '\n' ...
    'isSlow = 0;\n' ...
    'if rand() < prob_slow\n' ...
    '    isSlow = 1;\n' ...
    'end\n' ...
    'end', datestr(now), parametros.prob_AM, parametros.prob_slow_AM, parametros.prob_slow_FM);

% Guardar códigos en archivos
fid1 = fopen('output\InterArrival_General_code.m', 'w');
fwrite(fid1, codigo_interarrival, 'char');
fclose(fid1);

fid2 = fopen('output\Assign_Cliente_code.m', 'w');
fwrite(fid2, codigo_assign, 'char');
fclose(fid2);

fprintf('? Código generado en:\n');
fprintf('   - InterArrival_General_code.m\n');
fprintf('   - Assign_Cliente_code.m\n');
end